# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('square', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('price_per_m2', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('price', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('comments', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u041f\u043e\u043c\u0435\u0449\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u041f\u043e\u043c\u0435\u0449\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/media/product_images/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.Room')),
            ],
            options={
                'verbose_name': '\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f',
                'verbose_name_plural': '\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_value', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('status_description', models.TextField(blank=True, default=None, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0442\u0443\u0441',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0443\u0441\u044b',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Status'),
        ),
    ]
