# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default=True, max_length=50, null=True)),
                ('customer_email', models.EmailField(blank=True, default=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, default=True, max_length=30, null=True)),
                ('comments', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u0417\u0430\u043a\u0430\u0437',
                'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b',
            },
        ),
        migrations.CreateModel(
            name='RoomInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default=True, max_length=50, null=True)),
                ('customer_email', models.EmailField(blank=True, default=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, default=True, max_length=30, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('room', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.Room')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u043c\u0435\u0449\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u041f\u043e\u043c\u0435\u0449\u0435\u043d\u0438\u044f',
            },
        ),
    ]
